"""Decision-authority boundary for the post-search simulation architecture.

Legacy whole-deck search, Structural simulation and Tactical diagnostics remain importable for
historical analysis, tests and diagnostics. They are not candidate-admission authorities for the
external candidate -> gameplay queue contract.
"""

from commander_lab.candidates.contracts import (
    STRUCTURAL_SIMULATION_CAN_DECLARE_OFFICIAL_WINNER,
    STRUCTURAL_SIMULATION_CAN_ELIMINATE_CANDIDATE,
    STRUCTURAL_SIMULATION_DECISION_AUTHORITY,
    STRUCTURAL_SIMULATION_REQUIRED_BEFORE_GAMEPLAY,
    TACTICAL_DECISION_AUTHORITY,
    XMAGE_TARGET_RULES_AUTHORITY,
)

LEGACY_WHOLE_DECK_SEARCH_PRE_SIMULATION_ADMISSION_AUTHORITY = False
LEGACY_OPTIMIZER_V2_PRE_SIMULATION_ADMISSION_AUTHORITY = False
FIDELITY_ROUTING_PRE_SIMULATION_ADMISSION_AUTHORITY = False
QD_ARCHIVE_PRE_SIMULATION_ADMISSION_AUTHORITY = False
CURRENT_NEARNESS_PRE_SIMULATION_ADMISSION_AUTHORITY = False
OBJECTIVE_PRIOR_PRE_SIMULATION_ADMISSION_AUTHORITY = False
META_DISTANCE_PRE_SIMULATION_ADMISSION_AUTHORITY = False

LEGACY_DECK_GENERATION_STATUS = "DEPRECATED_FOR_SIMULATION_INPUT"
LEGACY_STRUCTURAL_STATUS = "DIAGNOSTIC_ONLY"
LEGACY_TACTICAL_STATUS = "BOUNDED_DIAGNOSTIC_TEST_SUPPORT"
GAMEPLAY_ENGINE_TARGET = "XMAGE"
DECISION_POLICY_TARGET = "OUR_PILOTS"
LAB_ROLE = "EXPERIMENT_EVIDENCE_CONTROLLER"

__all__ = [
    "CURRENT_NEARNESS_PRE_SIMULATION_ADMISSION_AUTHORITY",
    "DECISION_POLICY_TARGET",
    "FIDELITY_ROUTING_PRE_SIMULATION_ADMISSION_AUTHORITY",
    "GAMEPLAY_ENGINE_TARGET",
    "LAB_ROLE",
    "LEGACY_DECK_GENERATION_STATUS",
    "LEGACY_OPTIMIZER_V2_PRE_SIMULATION_ADMISSION_AUTHORITY",
    "LEGACY_STRUCTURAL_STATUS",
    "LEGACY_TACTICAL_STATUS",
    "LEGACY_WHOLE_DECK_SEARCH_PRE_SIMULATION_ADMISSION_AUTHORITY",
    "META_DISTANCE_PRE_SIMULATION_ADMISSION_AUTHORITY",
    "OBJECTIVE_PRIOR_PRE_SIMULATION_ADMISSION_AUTHORITY",
    "QD_ARCHIVE_PRE_SIMULATION_ADMISSION_AUTHORITY",
    "STRUCTURAL_SIMULATION_CAN_DECLARE_OFFICIAL_WINNER",
    "STRUCTURAL_SIMULATION_CAN_ELIMINATE_CANDIDATE",
    "STRUCTURAL_SIMULATION_DECISION_AUTHORITY",
    "STRUCTURAL_SIMULATION_REQUIRED_BEFORE_GAMEPLAY",
    "TACTICAL_DECISION_AUTHORITY",
    "XMAGE_TARGET_RULES_AUTHORITY",
]
