#!/usr/bin/env python3
"""Dispatch and watch `/oc` and `/bunny` work without hand-written walls of text.

    oc_dispatch.py post --issue N --lane oc|bunny --task FILE [--branch B] [--dry-run]
    oc_dispatch.py watch RUN | --issue N [--interval 60] [--timeout 7200]
    oc_dispatch.py rescue RUN [--out DIR]

``post`` builds the comment from a short task file plus a fixed footer (commit
trailers, evidence rules, no force-push, and open-PR-never-merge for `/oc`) and
creates it with `gh api`. ``watch`` waits the way ``gh_ops.py`` does - run it in
the background, never poll in the foreground - and then prints at most 15 lines:
outcome, branch, PR, test summary and the UNKNOWN/BLOCKED items from the bot's
final comment (or from the PR body the action created). It is read-only except
for the single comment ``post`` creates. ``rescue`` downloads the
``opencode-rescue-*`` artifact a failed or cancelled run leaves behind (its
action token expires after an hour, so a long run cannot push) and prints what it
holds plus the commands to recover the work; it pushes nothing itself.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

DEFAULT_REPO = "moeendres-png/commander-playtest-lab"
OPENCODE_WORKFLOW = "opencode.yml"
TRAILER = (
    "Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\n"
    "Claude-Session: https://claude.ai/code/session_01XoAKQUxcwkMyLLNvET1KVq"
)
CREATED_PR = re.compile(r"Created PR #(\d+)")
TEST_SUMMARY = re.compile(
    r"(\d[\d,]*\s+passed|\d[\d,]*\s+failed|Tests run:[^\n]*|\d+\s+run,\s*\d+\s+failures?[^\n]*"
    r"|BUILD (?:SUCCESS|FAILURE)|\d+\s+failures?\b)",
    re.IGNORECASE,
)
CANONICAL_NON_CREDIT = re.compile(r"\b(UNKNOWN|BLOCKED)\b")


def api(path: str, *, body: dict[str, Any] | None = None) -> Any:
    cmd = ["gh", "api", path]
    payload: str | None = None
    if body is not None:
        cmd = ["gh", "api", "-X", "POST", path, "--input", "-"]
        payload = json.dumps(body)
    out = subprocess.run(cmd, input=payload, capture_output=True, text=True, check=False)
    if out.returncode != 0:
        raise SystemExit(f"gh api {path}: {out.stderr.strip() or out.stdout.strip()}")
    return json.loads(out.stdout or "null")


def footer(lane: str) -> str:
    """The fixed footer every dispatched comment carries."""
    rules = [
        "**Rules.** No force-push, no history rewrite, no `reset --hard`, and no push to "
        "`main`/`master`.",
    ]
    if lane == "oc":
        rules.append(
            "Open a PR against `main` and never merge it. Work only on your own branch and do "
            "not touch another workstream's files. Never write a GitHub closing keyword "
            "(`Closes`, `Fixes`, `Resolves` followed by an issue number) in a commit message or "
            "the PR body: merging would close the issue. Use `Refs #N`; the Coordinator closes "
            "issues."
        )
    else:
        rules.append(
            "Read-only: change no code, create no branch, commit or push. Post your findings as "
            "one comment on this issue."
        )
    rules.append(
        "**Evidence.** `UNKNOWN != PASS`, `NOT_RUN != PASS`, and a green check is not "
        "qualification credit. Paste real exit codes and the test summary line; never weaken an "
        "assertion, a denominator or an expected semantic to get green. State blocked and "
        "unverified items explicitly."
    )
    trailer = f"**Commit trailer.**\n```\n{TRAILER}\n```"
    return (
        "---\n\n"
        + "\n\n".join(rules)
        + "\n\n"
        + trailer
        + "\n\n_Generated by [Claude Code](https://claude.ai/code)_"
    )


def build_comment(lane: str, task_text: str, branch: str | None) -> str:
    prefix = "/oc" if lane == "oc" else "/bunny"
    text = re.sub(rf"^/{lane}\b\s*", "", task_text.strip()).strip()
    parts = [f"{prefix} {text}"]
    if branch:
        if lane == "oc":
            parts.append(
                f"**Branch.** Work on `{branch}` from current `main`; do not touch any other branch."
            )
        else:
            parts.append(f"**Branch.** Audit `{branch}` read-only; do not create branches or PRs.")
    parts.append(footer(lane))
    return "\n\n".join(parts)


def cmd_post(a: argparse.Namespace) -> None:
    task = a.task.read_text(encoding="utf-8")
    body = build_comment(a.lane, task, a.branch)
    if a.dry_run:
        print(body)
        return
    created = api(f"repos/{a.repo}/issues/{a.issue}/comments", body={"body": body})
    if isinstance(created, dict) and created.get("html_url"):
        print(f"posted {created['html_url']}")
    else:
        print("posted (no html_url in response)")


def find_comment(repo: str, run_id: int, issue: int | None) -> dict[str, Any] | None:
    """The bot comment whose footer links this run."""
    needle = f"/actions/runs/{run_id}"
    if issue is not None:
        comments = api(f"repos/{repo}/issues/{issue}/comments?per_page=100") or []
    else:
        comments = (
            api(f"repos/{repo}/issues/comments?sort=created&direction=desc&per_page=100") or []
        )
    for c in comments:
        if needle in (c.get("body") or ""):
            return c
    return None


SETTLE_SECONDS = 30


def resolve_run(repo: str, issue: int, interval: int, timeout: int) -> dict[str, Any]:
    """Newest opencode run for an issue, waiting briefly for a just-posted one to appear."""
    title = api(f"repos/{repo}/issues/{issue}")["title"]
    deadline = time.time() + timeout
    settle = time.time() + SETTLE_SECONDS
    while True:
        runs = (
            api(
                f"repos/{repo}/actions/workflows/{OPENCODE_WORKFLOW}/runs"
                "?per_page=30&event=issue_comment"
            )
            or {}
        ).get("workflow_runs", [])
        matches = [r for r in runs if r.get("display_title") == title]
        active = [r for r in matches if r["status"] != "completed"]
        if active:
            return max(active, key=lambda r: r["created_at"])
        if matches and time.time() >= settle:
            return max(matches, key=lambda r: r["created_at"])
        if time.time() > deadline:
            raise SystemExit(f"no opencode workflow run for issue #{issue} after {timeout}s")
        time.sleep(min(interval, 5) if time.time() < settle else interval)


def wait_run(repo: str, run_id: int, interval: int, timeout: int) -> dict[str, Any]:
    deadline = time.time() + timeout
    while True:
        run = api(f"repos/{repo}/actions/runs/{run_id}")
        if run["status"] == "completed" or time.time() > deadline:
            return run
        time.sleep(interval)


def test_summary_line(report: str) -> str | None:
    for raw in report.splitlines():
        line = raw.strip().lstrip("|").strip()
        if not line or line.startswith("|"):
            continue
        match = TEST_SUMMARY.search(line)
        if match:
            return re.sub(r"[`*]+", "", line)[:160]
    return None


def non_credit_items(report: str, cap: int = 5) -> list[str]:
    """UNKNOWN/BLOCKED lines, plus the lines of an explicit blockers/unknowns section."""
    found: list[str] = []
    seen: set[str] = set()

    def add(text: str) -> None:
        cleaned = re.sub(r"^[-*>#\s]+", "", re.sub(r"[`*]+", "", text)).strip()
        if cleaned and cleaned not in seen and len(found) < cap:
            seen.add(cleaned)
            found.append(cleaned[:150])

    in_section = False
    for raw in report.splitlines():
        line = raw.strip()
        heading = line.lstrip("#* ").lower()
        if line.startswith(("#", "**")):
            in_section = any(word in heading for word in ("blocker", "unknown", "unverified"))
            continue
        if CANONICAL_NON_CREDIT.search(line) or (in_section and line):
            add(line)
    return found


def cmd_watch(a: argparse.Namespace) -> None:
    if a.run is None and a.issue is None:
        raise SystemExit("watch needs a RUN id or --issue N")
    if a.run is None:
        resolved = resolve_run(a.repo, a.issue, a.interval, a.timeout)
        run = wait_run(a.repo, resolved["id"], a.interval, a.timeout)
    else:
        run = wait_run(a.repo, a.run, a.interval, a.timeout)
    run_id = run["id"]
    issue = a.issue
    comment = find_comment(a.repo, run_id, issue)
    if issue is None and comment is not None:
        m = re.search(r"/issues/(\d+)$", comment.get("issue_url") or "")
        issue = int(m.group(1)) if m else None
    jobs = api(f"repos/{a.repo}/actions/runs/{run_id}/jobs?per_page=50")["jobs"]
    lane_jobs = [
        j for j in jobs if not (j.get("status") == "completed" and j.get("conclusion") == "skipped")
    ]
    lane = "bunny" if any("bunny" in j["name"] for j in lane_jobs) else "oc"
    job_state = next((j.get("conclusion") or j.get("status") for j in lane_jobs), "no job")

    report, link, branch, pr_number = "", run["html_url"], None, None
    if comment is not None:
        link = comment.get("html_url", link)
        report = comment.get("body") or ""
        created = CREATED_PR.search(report)
        if created:
            pr_number = int(created.group(1))
            pull = api(f"repos/{a.repo}/pulls/{pr_number}")
            report = pull.get("body") or ""
            branch = pull["head"]["ref"]
    if not report and issue is not None:
        target = api(f"repos/{a.repo}/issues/{issue}")
        if "pull_request" in target:
            branch = api(f"repos/{a.repo}/pulls/{issue}")["head"]["ref"]
            pr_number = pr_number or issue

    state = "running" if run["status"] != "completed" else str(run.get("conclusion"))
    outcome = state if state == job_state else f"{state} (job {job_state})"
    print(f"run {run_id} {lane} {outcome}")
    location = f"branch {branch}" if branch else "branch -"
    if pr_number:
        location += f", PR #{pr_number}"
    print(location)
    print(f"report {link}")
    if report:
        tests = test_summary_line(report)
        print(f"tests {tests or 'no test summary line in the report'}")
        items = non_credit_items(report)
        print(f"unknown/blocked {len(items)}")
        for item in items:
            print(f"- {item}")
    else:
        print("tests no report comment (the run posted nothing)")


RESCUE_ARTIFACT = re.compile(r"^opencode-rescue-")


def cmd_rescue(a: argparse.Namespace) -> None:
    artifacts = api(f"repos/{a.repo}/actions/runs/{a.run}/artifacts").get("artifacts", [])
    names = [
        x["name"] for x in artifacts if RESCUE_ARTIFACT.match(x["name"]) and not x.get("expired")
    ]
    if not names:
        print(f"run {a.run}: no unexpired opencode-rescue artifact")
        return
    for name in names:
        out = Path(a.out) / name
        out.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["gh", "run", "download", str(a.run), "-R", a.repo, "-n", name, "-D", str(out)],
            check=True,
        )
        print(f"{name} -> {out}")
        for part in ("log.txt", "status.txt"):
            path = out / part
            if path.exists():
                lines = path.read_text(encoding="utf-8", errors="replace").splitlines()[:10]
                print(f"  {part}: " + (" | ".join(lines) if lines else "(empty)"))
        diff = out / "uncommitted.diff"
        if diff.exists() and diff.stat().st_size:
            print(f"  uncommitted diff: {diff.stat().st_size} bytes -> git apply {diff}")
        bundle = out / "work.bundle"
        if bundle.exists():
            print(
                f"  recover (in a full clone; the bundle is cut from a shallow checkout): "
                f"git fetch {bundle} 'refs/heads/*:refs/remotes/rescue-{a.run}/*'"
            )


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="command", required=True)
    post = sub.add_parser("post", help="create a /oc or /bunny dispatch comment")
    post.add_argument("--issue", type=int, required=True)
    post.add_argument("--lane", choices=["oc", "bunny"], required=True)
    post.add_argument("--task", type=Path, required=True, help="task skeleton to fill in")
    post.add_argument("--branch", help="branch to work on (oc) or audit (bunny)")
    post.add_argument("--repo", default=DEFAULT_REPO)
    post.add_argument("--dry-run", action="store_true", help="print the comment, post nothing")
    watch = sub.add_parser("watch", help="wait for a run and print its compact outcome")
    watch.add_argument("run", nargs="?", type=int, help="workflow run id")
    watch.add_argument("--issue", type=int, help="wait for the issue's newest opencode run")
    watch.add_argument("--repo", default=DEFAULT_REPO)
    watch.add_argument("--interval", type=int, default=60)
    watch.add_argument("--timeout", type=int, default=7200)
    rescue = sub.add_parser("rescue", help="download a failed run's unpublished work")
    rescue.add_argument("run", type=int, help="workflow run id")
    rescue.add_argument("--repo", default=DEFAULT_REPO)
    rescue.add_argument("--out", default="opencode-rescue", help="download directory")
    a = parser.parse_args()
    {"post": cmd_post, "watch": cmd_watch, "rescue": cmd_rescue}[a.command](a)


if __name__ == "__main__":
    sys.exit(main())
