from .cards import (
    CardCondition,
    CardIdentity,
    CardLegality,
    Collection,
    CommanderConfiguration,
    Deck,
    DeckEntry,
    DeckZone,
    PhysicalCard,
    PurchaseStatus,
)
from .common import Color, DataQuality, ErrorDetail, FrozenModel, MutableModel, NumericRange, SourceRef

from .engine_runtime import (
    ENGINE_PROTOCOL_VERSION,
    EngineCapabilityHandshake,
    EngineInstallationIdentity,
    EngineMessageType,
    EngineProcessState,
    EngineProcessStatus,
    EngineProtocolErrorDetail,
    EngineProtocolRequest,
    EngineProtocolResponse,
    EngineReplay,
    EngineResponseStatus,
    EngineRuntimeConfig,
    EngineRuntimeMode,
    RuntimeValidationLevel,
)

from .game import (
    ActionProposal,
    ActionType,
    GameEvent,
    GameState,
    GameStatus,
    LegalAction,
    PlayerState,
    TurnPhase,
    ZoneName,
    ZoneState,
)
from .opponents import OpponentListStatus, OpponentProfile, UncertaintyModel

from .optimization import (
    BeamSearchInput,
    CandidatePackage,
    ConstraintIssue,
    ConstraintReport,
    LocalSearchInput,
    ObjectiveVector,
    OptimizationConstraints,
    OptimizationObjective,
    OptimizationValidationInput,
    OptimizationVariant,
    PackageSearchInput,
    ParetoFrontInput,
    ShapleyInput,
)
from .roles import CardRole
from .pilots import (
    PilotActionView,
    PilotCommanderView,
    PilotConfig,
    PilotDecision,
    PilotDecisionMode,
    PilotEnsembleDefinition,
    PilotEnsembleMember,
    PilotInformationMode,
    PilotInformationPolicy,
    PilotOpponentView,
    PilotProfile,
    PilotStateView,
    PilotStrength,
    PilotUtilityBreakdown,
    PilotUtilityWeights,
)
from .structural import (
    STRUCTURAL_ESTIMATE_TYPE,
    ConditionalStrength,
    StructuralAbortLimits,
    StructuralBatchConfig,
    StructuralBatchResult,
    StructuralCardProfile,
    StructuralDeckProfile,
    StructuralMatchConfig,
    StructuralMatchResult,
    StructuralPlayerMetrics,
)

from .rules import (
    BridgeRequest,
    BridgeResponse,
    CardValidationRecord,
    InteractionSpec,
    InteractionValidation,
    RulesBackend,
    RulesDeckHandle,
    RulesDeckInput,
    RulesEngineAvailability,
    RulesEngineCapabilities,
    RulesEngineLog,
    RulesEngineProbe,
    RulesEngineResult,
    RulesGameRequest,
    RulesSession,
    TacticalScenario,
    ValidationLevel,
    ValidationRegistry,
)

from .meta import (
    META_SCHEMA_VERSION,
    BudgetBand,
    FormatBand,
    MetaArchetype,
    MetaCardFrequency,
    MetaCategory,
    MetaDeckSnapshot,
    MetaEvidenceRating,
    MetaKnowledgeBaseSnapshot,
    MetaPackage,
    MetaSnapshotManifest,
    MetaSource,
    PrimerReference,
    TournamentResult,
)

from .tooling import (
    BuildOptimizationContextInput,
    GenerateCandidateSwapsInput,
    GenerateCandidatePackagesInput,
    OptimizeDeckAgainstMetaInput,
    OptimizeMultipleDecksWithAllocationInput,
    ValidateSwapInput,
    ValidatePackageChangeInput,
    ValidateLandChangeInput,
    ValidateMulliganPolicyInput,
    RunMultifidelityComparisonInput,
    RunEngineBackedMatchupInput,
    RunRobustnessSuiteInput,
    RunRulesCoverageGateInput,
    RankVariantsInput,
    ExplainRecommendationInput,
    ExportRecommendationEvidenceInput,
    CreateDeckImprovementReportInput,
)

from .tooling import (
    ImportMetaDeckInput,
    ImportTournamentResultInput,
    ImportPrimerReferenceInput,
    CreateMetaSnapshotInput,
    QueryMetaCardsInput,
    QueryMetaPackagesInput,
    CompareDeckToMetaInput,
    CompareMetaPeriodsInput,
    GenerateMetaReportInput,
)

from .tooling import (
    ExtractArchetypesInput,
    ExtractPackagesInput,
    InspectPackageInput,
    ComparePackageVersionsInput,
    EvaluatePackageDensityInput,
    DetectOrphanedCardsInput,
    GeneratePackageReportInput,
)

from .primer import (
    PRIMER_RULE_SCHEMA_VERSION,
    ActionPreference,
    CompiledPilotPolicy,
    ConditionOperator,
    DecisionPoint,
    PilotRule,
    PilotRuleCondition,
    PolicyActionScore,
    PolicyDecisionTrace,
    PolicyEvalResult,
    PolicyEvalScenario,
    PrimerDocument,
    PrimerEvidenceType,
    PrimerFormat,
    PrimerRegistry,
    PrimerRuleConflict,
    PrimerRuleStatus,
    RuleValidationIssue,
    RuleValidationReport,
)

from .packages import (
    PACKAGE_SCHEMA_VERSION,
    ArchetypeName,
    ArchetypeProfile,
    ArchetypeWeight,
    ExtractionMethod,
    PackageDefinition,
    PackageEvaluation,
    PackageRegistry,
    PackageStatus,
    PackageVersionComparison,
)


from .provenance import (
    PROVENANCE_SCHEMA_VERSION, ArtifactRecord, CitationRecord, ClaimKind,
    DerivedDataRecord, LicenseRecord, ProvenanceGraph, SourceRecord, SourceType,
    SupersessionRecord, TransformationRecord, VerificationStatus,
)

from .simulation import (
    CardContribution,
    CardSwap,
    MatchResult,
    RunStatus,
    SimulationConfig,
    SimulationMode,
    SimulationRun,
    UpgradeProposal,
    UpgradeStatus,
)

__all__ = [
    "ActionProposal",
    "ActionType",
    "CardCondition",
    "CardContribution",
    "CardIdentity",
    "CardLegality",
    "CardSwap",
    "Collection",
    "Color",
    "CommanderConfiguration",
    "DataQuality",
    "Deck",
    "DeckEntry",
    "DeckZone",
    "ErrorDetail",
    "FrozenModel",
    "GameEvent",
    "GameState",
    "GameStatus",
    "LegalAction",
    "MatchResult",
    "MutableModel",
    "NumericRange",
    "OpponentListStatus",
    "OpponentProfile",
    "PhysicalCard",
    "PlayerState",
    "PilotActionView",
    "PilotCommanderView",
    "PilotConfig",
    "PilotDecision",
    "PilotDecisionMode",
    "PilotEnsembleDefinition",
    "PilotEnsembleMember",
    "PilotInformationMode",
    "PilotInformationPolicy",
    "PilotOpponentView",
    "PilotProfile",
    "PilotStateView",
    "PilotStrength",
    "PilotUtilityBreakdown",
    "PilotUtilityWeights",
    "PurchaseStatus",
    "RunStatus",
    "SimulationConfig",
    "SimulationMode",
    "SimulationRun",
    "SourceRef",
    "TurnPhase",
    "UncertaintyModel",
    "UpgradeProposal",
    "UpgradeStatus",
    "ZoneName",
    "STRUCTURAL_ESTIMATE_TYPE",
    "CardRole",
    "ConditionalStrength",
    "StructuralAbortLimits",
    "StructuralBatchConfig",
    "StructuralBatchResult",
    "StructuralCardProfile",
    "StructuralDeckProfile",
    "StructuralMatchConfig",
    "StructuralMatchResult",
    "StructuralPlayerMetrics",
    "BeamSearchInput",
    "CandidatePackage",
    "ConstraintIssue",
    "ConstraintReport",
    "LocalSearchInput",
    "ObjectiveVector",
    "OptimizationConstraints",
    "OptimizationObjective",
    "OptimizationValidationInput",
    "OptimizationVariant",
    "PackageSearchInput",
    "ParetoFrontInput",
    "ShapleyInput",
    "ZoneState",
    "META_SCHEMA_VERSION",
    "BudgetBand",
    "FormatBand",
    "MetaArchetype",
    "MetaCardFrequency",
    "MetaCategory",
    "MetaDeckSnapshot",
    "MetaEvidenceRating",
    "MetaKnowledgeBaseSnapshot",
    "MetaPackage",
    "MetaSnapshotManifest",
    "MetaSource",
    "PrimerReference",
    "TournamentResult",
    "BridgeRequest",
    "BridgeResponse",
    "CardValidationRecord",
    "InteractionSpec",
    "InteractionValidation",
    "RulesBackend",
    "RulesDeckHandle",
    "RulesDeckInput",
    "RulesEngineAvailability",
    "RulesEngineCapabilities",
    "RulesEngineLog",
    "RulesEngineProbe",
    "RulesEngineResult",
    "RulesGameRequest",
    "RulesSession",
    "TacticalScenario",
    "ValidationLevel",
    "ValidationRegistry",
    "ENGINE_PROTOCOL_VERSION",
    "EngineCapabilityHandshake",
    "EngineInstallationIdentity",
    "EngineMessageType",
    "EngineProcessState",
    "EngineProcessStatus",
    "EngineProtocolErrorDetail",
    "EngineProtocolRequest",
    "EngineProtocolResponse",
    "EngineReplay",
    "EngineResponseStatus",
    "EngineRuntimeConfig",
    "EngineRuntimeMode",
    "RuntimeValidationLevel",
]


from .tooling import (
    CandidateProfile,
    CardAblationInput,
    CommanderDenialInput,
    CompareDecksInput,
    CostLimits,
    CreateReportInput,
    DeckRefInput,
    GoldfishInput,
    HoldoutInput,
    InspectDeckInput,
    MatchupBatchInput,
    PackageAblationInput,
    PairedVariantInput,
    RecommendUpgradesInput,
    SearchVariantsInput,
    SensitivityInput,
    SimulationInput,
    SwapMatrixInput,
    ToolExecutionMetadata,
    ToolResponse,
    ToolStatus,
    ValidateDeckInput,
    ValidateUpgradeInput,
    VariantSwap,
    WorkflowReport,
    WorkflowRequest,
    ImportPrimerInput,
    ExtractPrimerRulesInput,
    ValidatePilotRulesInput,
    CompilePilotPolicyInput,
    ComparePolicyVersionsInput,
    RunPolicyEvalInput,
    GeneratePrimerConflictReportInput,
    ListPilotProfilesInput,
    InspectPilotInput,
    RunPilotBenchmarkInput,
    ComparePilotsInput,
    PilotWeightInput,
    RunPilotEnsembleInput,
    TestVariantAcrossPilotsInput,
    GeneratePilotRobustnessReportInput,
)


__all__.extend([
    "PRIMER_RULE_SCHEMA_VERSION", "ActionPreference", "CompiledPilotPolicy",
    "ConditionOperator", "DecisionPoint", "PilotRule", "PilotRuleCondition",
    "PolicyActionScore", "PolicyDecisionTrace", "PolicyEvalResult", "PolicyEvalScenario",
    "PrimerDocument", "PrimerEvidenceType", "PrimerFormat", "PrimerRegistry",
    "PrimerRuleConflict", "PrimerRuleStatus", "RuleValidationIssue", "RuleValidationReport",
    "ImportPrimerInput", "ExtractPrimerRulesInput", "ValidatePilotRulesInput",
    "CompilePilotPolicyInput", "ComparePolicyVersionsInput", "RunPolicyEvalInput",
    "GeneratePrimerConflictReportInput",
    "ListPilotProfilesInput", "InspectPilotInput", "RunPilotBenchmarkInput",
    "ComparePilotsInput", "PilotWeightInput", "RunPilotEnsembleInput",
    "TestVariantAcrossPilotsInput", "GeneratePilotRobustnessReportInput",
])

from .tooling import (
    TraceArtifactProvenanceInput, TraceRecommendationSourcesInput,
    ListSupersededSourcesInput, VerifySourceHashInput,
    GenerateProvenanceReportInput, AuditUnreferencedClaimsInput,
)
__all__.extend([
    "PROVENANCE_SCHEMA_VERSION", "ArtifactRecord", "CitationRecord", "ClaimKind",
    "DerivedDataRecord", "LicenseRecord", "ProvenanceGraph", "SourceRecord",
    "SourceType", "SupersessionRecord", "TransformationRecord", "VerificationStatus",
    "TraceArtifactProvenanceInput", "TraceRecommendationSourcesInput",
    "ListSupersededSourcesInput", "VerifySourceHashInput",
    "GenerateProvenanceReportInput", "AuditUnreferencedClaimsInput",
])


from .opponent_ensembles import (OPPONENT_ENSEMBLE_SCHEMA_VERSION, ObservationStatus, EnsembleWeightMode, OpponentCardAssumption, ObservedConstraint, UncertaintyDimension, VariantWeight, OpponentVariant, OpponentEnsemble, RobustnessScenario, EnsembleMatchupResult)
from .tooling import (CreateOpponentEnsembleInput, AddOpponentVariantInput, ValidateEnsembleInput, RunEnsembleMatchupsInput, CompareVariantSensitivityInput, EvaluateRobustUpgradeInput, GenerateEnsembleReportInput)
__all__.extend(["OPPONENT_ENSEMBLE_SCHEMA_VERSION","ObservationStatus","EnsembleWeightMode","OpponentCardAssumption","ObservedConstraint","UncertaintyDimension","VariantWeight","OpponentVariant","OpponentEnsemble","RobustnessScenario","EnsembleMatchupResult","CreateOpponentEnsembleInput","AddOpponentVariantInput","ValidateEnsembleInput","RunEnsembleMatchupsInput","CompareVariantSensitivityInput","EvaluateRobustUpgradeInput","GenerateEnsembleReportInput"])

from .mulligan import (
    MULLIGAN_LAB_SCHEMA_VERSION,
    GeneratedKeepRule,
    HypergeometricBaseline,
    KeepRuleClause,
    LondonMulliganResult,
    MulliganContext,
    MulliganEstimateLevel,
    MulliganGamePlan,
    MulliganLabResult,
    MulliganPolicyName,
    MulliganPolicySummary,
    OpeningHandEvaluation,
    OpeningHandFeatures,
)
from .tooling import (
    SampleOpeningHandsInput,
    EvaluateOpeningHandInput,
    CompareMulliganPoliciesInput,
    RunMulliganLabInput,
    GenerateKeepRulesInput,
    TestKeepRuleInput,
    CreateMulliganReportInput,
)

__all__.extend([
    "MULLIGAN_LAB_SCHEMA_VERSION", "GeneratedKeepRule", "HypergeometricBaseline",
    "KeepRuleClause", "LondonMulliganResult", "MulliganContext",
    "MulliganEstimateLevel", "MulliganGamePlan", "MulliganLabResult",
    "MulliganPolicyName", "MulliganPolicySummary", "OpeningHandEvaluation",
    "OpeningHandFeatures", "SampleOpeningHandsInput", "EvaluateOpeningHandInput",
    "CompareMulliganPoliciesInput", "RunMulliganLabInput", "GenerateKeepRulesInput",
    "TestKeepRuleInput", "CreateMulliganReportInput",
])

from .counterfactual import (
    COUNTERFACTUAL_SCHEMA_VERSION,
    CounterfactualAction,
    CounterfactualBranchpoint,
    CounterfactualComparison,
    CounterfactualEngineMode,
    CounterfactualFutureSample,
    CounterfactualResult,
    CounterfactualStateDiff,
    DecisionRegretRecord,
    HiddenInformationPolicy,
    SeedPolicy,
)
from .tooling import (
    FindCounterfactualBranchpointsInput,
    ListAlternativeActionsInput,
    RunCounterfactualInput,
    CompareCounterfactualsInput,
    GenerateDecisionRegretReportInput,
    ExportMinimalCounterfactualFixtureInput,
)
__all__.extend([
    "COUNTERFACTUAL_SCHEMA_VERSION", "CounterfactualAction", "CounterfactualBranchpoint",
    "CounterfactualComparison", "CounterfactualEngineMode", "CounterfactualFutureSample",
    "CounterfactualResult", "CounterfactualStateDiff", "DecisionRegretRecord",
    "HiddenInformationPolicy", "SeedPolicy", "FindCounterfactualBranchpointsInput",
    "ListAlternativeActionsInput", "RunCounterfactualInput", "CompareCounterfactualsInput",
    "GenerateDecisionRegretReportInput", "ExportMinimalCounterfactualFixtureInput",
])

from .diagnostics import (
    DIAGNOSTIC_SCHEMA_VERSION,
    CardPerformanceInstrumentation,
    DiagnosisRecord,
    DiagnosticDataset,
    DiagnosticMetrics,
    FactorEffectComparison,
    FailureCause,
    IntegratedExtensionSmokeReport,
    IntegratedSmokeStep,
    PilotDiagnosticEvidence,
)
from .tooling import (
    DiagnoseCardPerformanceInput, DiagnosePilotBehaviorInput,
    CompareDeckAndPilotEffectsInput, ClassifyFailureCauseInput,
    RecommendNextExperimentInput, GenerateDiagnosticReportInput,
)
__all__.extend([
    "DIAGNOSTIC_SCHEMA_VERSION", "CardPerformanceInstrumentation", "DiagnosisRecord",
    "DiagnosticDataset", "DiagnosticMetrics", "FactorEffectComparison", "FailureCause",
    "IntegratedExtensionSmokeReport", "IntegratedSmokeStep", "PilotDiagnosticEvidence",
    "DiagnoseCardPerformanceInput", "DiagnosePilotBehaviorInput",
    "CompareDeckAndPilotEffectsInput", "ClassifyFailureCauseInput",
    "RecommendNextExperimentInput", "GenerateDiagnosticReportInput",
])

__all__.extend([
    "BuildOptimizationContextInput", "GenerateCandidateSwapsInput",
    "GenerateCandidatePackagesInput", "OptimizeDeckAgainstMetaInput",
    "OptimizeMultipleDecksWithAllocationInput", "ValidateSwapInput",
    "ValidatePackageChangeInput", "ValidateLandChangeInput",
    "ValidateMulliganPolicyInput", "RunMultifidelityComparisonInput",
    "RunEngineBackedMatchupInput", "RunRobustnessSuiteInput",
    "RunRulesCoverageGateInput", "RankVariantsInput",
    "ExplainRecommendationInput", "ExportRecommendationEvidenceInput",
    "CreateDeckImprovementReportInput",
])
