#!/usr/bin/env python3
"""RQ-A2 U5 — mechanical real-card <-> behavior-test linkage inventory.

Read-only over the Argentum candidate checkout at the exact lock. No build,
no test execution, no heuristics beyond the documented name-matching rules.
Ambiguous cases stay UNKNOWN (filename heuristics are never proof).

Classes (per contract):
  DECLARED_CARD_NAME, CANONICAL_CARD_IMPLEMENTATION, GENERATED_DRAFT_OR_NONCANONICAL,
  COMPILES_OR_LOADS, MENTIONED_IN_TEST, BEHAVIOR_ORIENTED_TEST,
  MULTIPLAYER_BEHAVIOR_TEST, COMMANDER_BEHAVIOR_TEST, UNKNOWN
"""
import json
import re
import sys
from pathlib import Path

CAND = Path("/tmp/rq-a2-argentum-src")
OUT = Path("/home/moeen/code/rq-a2-argentum-comparable-qualification"
           "/research/candidate-qualification/argentum/rq-a2/evidence")

CARD_RE = re.compile(r'\b(?:card|basicLand)\("((?:[^"\\]|\\.)*)"')
PRINTING_NAME_RE = re.compile(r'name\s*=\s*"((?:[^"\\]|\\.)*)"')
GENERATED_MARK = "GENERATED by mtgish"
LITERAL_RE = re.compile(r'"((?:[^"\\]|\\.){1,80})"')
DRIVER_PATTERNS = re.compile(
    r"ScenarioTestBase|GameTestDriver|EnumerationTestDriver|initMultiplayer|"
    r"initGame|initMirrorMatch|putCreatureOnBattlefield|putPermanentOnBattlefield|"
    r"putCardInHand|putLandOnBattlefield|passPriority|submitSuccess|castSpell|"
    r"playLand|declareAttackers|declareBlockers|withCardOnBattlefield|withCardInHand|"
    r"ScenarioBuilder|driver\.")
MULTI_PATTERNS = re.compile(
    r"initMultiplayer|playerCount\s*=\s*[3-9]|List\(4\)|List\(5\)|TwoHeadedGiant|"
    r"TeamVsTeam|Multiplayer|CommanderPod|AttackModeTest|initGame\(4\)|initGame\(3\)|"
    r"initGame\(5\)")
COMMANDER_PATTERNS = re.compile(
    r"Format\.Commander|commanderCardName|CommanderSetup|CommanderTax|CommanderPod|"
    r"CommanderDamage|CommanderZone|commanderDamage|COMMANDER")


def norm(s):
    return re.sub(r"[^a-z0-9]", "", s.lower())


def main():
    impls = {}   # name -> {"files": set, "generated": bool}
    reprints = {}  # name -> count
    card_files = 0
    for f in list((CAND / "mtg-sets").rglob("src/main/**/*.kt")):
        card_files += 1
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        generated = GENERATED_MARK in text
        for m in CARD_RE.finditer(text):
            name = m.group(1)
            e = impls.setdefault(name, {"files": set(), "generated": False})
            e["files"].add(str(f.relative_to(CAND)))
            e["generated"] = e["generated"] or generated
    # reprint rows: Printing( ... name = "..." ...) in main sources
    for f in list((CAND / "mtg-sets").rglob("src/main/**/*.kt")):
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if "Printing(" not in text:
            continue
        for m in PRINTING_NAME_RE.finditer(text):
            reprints[m.group(1)] = reprints.get(m.group(1), 0) + 1

    declared = set(impls) | set(reprints)

    # ---- tests ----
    test_roots = [
        CAND / "rules-engine/src/test",
        CAND / "game-server/src/test",
        CAND / "gym/src/test",
        CAND / "gym-server/src/test",
        CAND / "gym-trainer/src/test",
    ]
    test_roots += [p for p in (CAND / "mtg-sets").glob("*/tests/src/test")]
    test_files = []
    for r in test_roots:
        if r.is_dir():
            test_files += list(r.rglob("*Test.kt"))
    e2e_files = list((CAND / "e2e-scenarios/tests").rglob("*.spec.ts")) if (CAND / "e2e-scenarios/tests").is_dir() else []
    manual_files = list((CAND / "manual-scenarios").rglob("*.json")) if (CAND / "manual-scenarios").is_dir() else []

    # named-class linkage: normalized file name vs normalized card name
    norm_to_names = {}
    for n in declared:
        norm_to_names.setdefault(norm(n), []).append(n)
    named_link = {}  # name -> [test files]
    for f in test_files:
        stem = f.stem
        for suffix in ("ScenarioTest", "MultiplayerTest", "CommanderTest", "Test", "Spec"):
            if stem.endswith(suffix) and len(stem) > len(suffix):
                stem = stem[: -len(suffix)]
                break
        for n in norm_to_names.get(norm(stem), []):
            named_link.setdefault(n, []).append(str(f.relative_to(CAND)))

    mentioned = {}  # name -> {"unit": n files, "manual": n, "e2e": n}
    behavior = {}   # name -> [files] (driver pattern + quoted mention)
    multi_files = set()
    commander_files = set()
    driver_files = 0
    for f in test_files:
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        is_driver = bool(DRIVER_PATTERNS.search(text))
        if is_driver:
            driver_files += 1
        if MULTI_PATTERNS.search(text):
            multi_files.add(str(f.relative_to(CAND)))
        if COMMANDER_PATTERNS.search(text):
            commander_files.add(str(f.relative_to(CAND)))
        lits = set(LITERAL_RE.findall(text))
        hits = [n for n in declared if n in lits]
        for n in hits:
            e = mentioned.setdefault(n, {"unit": 0, "manual": 0, "e2e": 0})
            e["unit"] += 1
            if is_driver:
                behavior.setdefault(n, []).append(str(f.relative_to(CAND)))
    for f in manual_files:
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        lits = set(LITERAL_RE.findall(text))
        for n in declared:
            if n in lits:
                mentioned.setdefault(n, {"unit": 0, "manual": 0, "e2e": 0})["manual"] += 1
    for f in e2e_files:
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        lits = set(LITERAL_RE.findall(text))
        for n in declared:
            if n in lits:
                mentioned.setdefault(n, {"unit": 0, "manual": 0, "e2e": 0})["e2e"] += 1

    behavior_named = {n: files for n, files in named_link.items()}
    # union behavior: named-class OR driver-mention
    behavior_all = {n: sorted(set(named_link.get(n, []) + behavior.get(n, []))) for n in set(named_link) | set(behavior)}

    multi_cards = {n: sorted(set(behavior_all.get(n, [])) & multi_files) for n in behavior_all
                   if set(behavior_all[n]) & multi_files}
    commander_cards = {n: sorted(set(behavior_all.get(n, [])) & commander_files) for n in behavior_all
                       if set(behavior_all[n]) & commander_files}

    generated_names = sorted(n for n, e in impls.items() if e["generated"])
    canonical_names = sorted(n for n, e in impls.items() if not e["generated"])
    unknown = sorted(n for n in declared if n not in mentioned and n not in named_link)

    result = {
        "methodology": {
            "candidate": "wingedsheep/argentum-engine @ 3f46367d87c88bcf156a843a9e69fd29e1693872",
            "cardRegex": "\\b(?:card|basicLand)\\(\"…\"\\) over mtg-sets/*/src/main/**/*.kt",
            "generatedMark": "header comment 'GENERATED by mtgish'",
            "reprintRegex": "name = \"…\" in files containing Printing(",
            "namedClassRule": "test file stem minus Test/ScenarioTest/Spec suffix, lowercased alnum, equals normalized card name",
            "driverMentionRule": "quoted card-name literal in a *Test.kt using driver/scenario patterns (heuristic, reported separately)",
            "mentionedRule": "quoted literal anywhere in unit/manual/e2e tests (noisy for basics; reported separately)",
            "multiRule": "behavior-linked file also matches multiplayer patterns",
            "commanderRule": "behavior-linked file also matches commander patterns",
            "unknownRule": "declared but zero test signal of any kind",
        },
        "counts": {
            "cardSourceFiles": card_files,
            "declaredNames": len(declared),
            "canonicalImplementations": len(canonical_names),
            "generatedDrafts": len(generated_names),
            "reprintRowNames": len(reprints),
            "reprintRows": sum(reprints.values()),
            "testFilesScanned": len(test_files),
            "driverPatternFiles": driver_files,
            "e2eSpecs": len(e2e_files),
            "manualScenarios": len(manual_files),
            "namedTestClassLinks": len(behavior_named),
            "driverMentionLinks": len(behavior),
            "behaviorUnion": len(behavior_all),
            "mentionedUnion": len(mentioned),
            "multiplayerBehavior": len(multi_cards),
            "commanderBehavior": len(commander_cards),
            "unknown": len(unknown),
        },
        "behaviorCards": sorted(behavior_all),
        "multiplayerBehaviorCards": sorted(multi_cards),
        "commanderBehaviorCards": sorted(commander_cards),
        "note": "Full per-card file lists omitted for size; linkage DB reproducible via this script. Basics (Forest etc.) dominate MENTIONED counts; see report for the basics breakout.",
    }
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "ARGENTUM_CARD_BEHAVIOR_LINKAGE.json").write_text(json.dumps(result, indent=1))
    # basics breakout to stdout
    basics = ["Plains", "Island", "Swamp", "Mountain", "Forest"]
    for b in basics:
        print(b, mentioned.get(b), "named:", named_link.get(b))
    print("counts:", json.dumps(result["counts"], indent=1))
    # top multiplayer/commander cards
    print("multi:", sorted(multi_cards)[:30])
    print("commander:", sorted(commander_cards)[:30])


if __name__ == "__main__":
    sys.exit(main())
