#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

# Match method declarations only. In particular, do not let the outer
# `public abstract class PlayerController { ...` declaration consume text up
# to the first semicolon and masquerade as an abstract callback.
ABSTRACT_METHOD_RE = re.compile(
    r"\b(public|protected)\s+abstract\s+"
    r"(?!class\b|interface\b|enum\b|record\b)"
    r"([^;{}]+?\([^;{}]*\)(?:\s+throws\s+[^;{}]+)?);",
    re.DOTALL,
)
CONCRETE_METHOD_RE = re.compile(
    r"\b(public|protected)\s+(?!abstract\b)(?:final\s+)?(?:<[^>{}]+>\s+)?[^;{}=]+?\b([A-Za-z_$][\w$]*)\s*\([^;{}]*\)\s*\{",
    re.DOTALL,
)
METHOD_NAME_RE = re.compile(r"([A-Za-z_$][\w$]*)\s*\(")
REMOTE_DEFAULT_RE = re.compile(r"result\s*!=\s*null\s*\?\s*result\s*:\s*(default[A-Za-z0-9_$]+)")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", text)


def normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def method_name(signature: str) -> str:
    matches = METHOD_NAME_RE.findall(signature)
    if not matches:
        raise ValueError(f"cannot determine method name: {signature}")
    return matches[-1]


def abstract_methods(source: str) -> list[dict[str, str]]:
    cleaned = strip_comments(source)
    methods: list[dict[str, str]] = []
    seen: set[str] = set()
    for match in ABSTRACT_METHOD_RE.finditer(cleaned):
        signature = normalize_space(f"{match.group(1)} {match.group(2)}")
        if "{" in signature or "}" in signature or "=" in signature.split("(", 1)[0]:
            raise ValueError(f"non-method text entered abstract callback inventory: {signature}")
        name = method_name(signature)
        if signature in seen:
            raise ValueError(f"duplicate abstract signature: {signature}")
        seen.add(signature)
        methods.append({"name": name, "signature": signature})
    if not methods:
        raise ValueError("no abstract PlayerController methods found")
    return methods


def concrete_methods(source: str) -> list[str]:
    cleaned = strip_comments(source)
    names: list[str] = []
    for match in CONCRETE_METHOD_RE.finditer(cleaned):
        name = match.group(2)
        if name not in names:
            names.append(name)
    return names


def render_strict_controller(source: str, methods: list[dict[str, str]]) -> str:
    package = re.search(r"(?m)^package\s+([^;]+);", source)
    if not package:
        raise ValueError("PlayerController package declaration missing")
    imports = re.findall(r"(?m)^import\s+[^;]+;", source)
    lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by Commander Simulation Foundry WS-19 from the pinned Forge PlayerController surface.",
        f"package {package.group(1)};",
        "",
        *imports,
        "",
        "public final class StrictExternalPlayerControllerGenerated extends PlayerController {",
        "    public StrictExternalPlayerControllerGenerated(Game game, Player player, LobbyPlayer lobbyPlayer) {",
        "        super(game, player, lobbyPlayer);",
        "    }",
        "",
        "    private RuntimeException failClosed(String method) {",
        '        return new UnsupportedOperationException("WS19_UNROUTED_DECISION:" + method);',
        "    }",
        "",
    ]
    for item in methods:
        lines.extend(
            [
                "    @Override",
                f"    {item['signature']} {{",
                f'        throw failClosed("{item["name"]}");',
                "    }",
                "",
            ]
        )
    lines.extend(["}", ""])
    return "\n".join(lines)


def java_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_probe_provider(
    *, forge_commit: str, forge_tree: str, forge_version: str, abstract_count: int
) -> str:
    return f'''// SPDX-License-Identifier: GPL-3.0-or-later
package forge.game.player;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public final class Ws19ForgeProbeProvider {{
    private static final String PROTOCOL = "commander-lab.rules-service/1.1.0";
    private static final String FORGE_COMMIT = "{java_string(forge_commit)}";
    private static final String FORGE_TREE = "{java_string(forge_tree)}";
    private static final String FORGE_VERSION = "{java_string(forge_version)}";
    private static final int GENERATED_ABSTRACT_COUNT = {abstract_count};

    private static String jsonString(String value) {{
        if (value == null) return "null";
        return "\\\"" + value.replace("\\\\", "\\\\\\\\").replace("\\\"", "\\\\\\\"").replace("\\n", "\\\\n") + "\\\"";
    }}

    private static String extract(String body, String key) {{
        Pattern p = Pattern.compile("\\\"" + Pattern.quote(key) + "\\\"\\\\s*:\\s*\\\"((?:\\\\\\\\.|[^\\\"\\\\\\\\])*)\\\"");
        Matcher m = p.matcher(body);
        if (!m.find()) return null;
        return m.group(1).replace("\\\\\\\"", "\\\"").replace("\\\\n", "\\n").replace("\\\\\\\\", "\\\\");
    }}

    private static boolean classPresent(String name) {{
        try {{
            Class.forName(name, false, Ws19ForgeProbeProvider.class.getClassLoader());
            return true;
        }} catch (ClassNotFoundException expected) {{
            return false;
        }}
    }}

    private static int abstractPlayerControllerCount() {{
        int count = 0;
        for (Method method : PlayerController.class.getDeclaredMethods()) {{
            if (Modifier.isAbstract(method.getModifiers())) count++;
        }}
        return count;
    }}

    private static String response(String requestId, String messageType, String verdict, String reason) {{
        int runtimeAbstractCount = abstractPlayerControllerCount();
        boolean strictDirect = StrictExternalPlayerControllerGenerated.class.getSuperclass() == PlayerController.class;
        boolean aiPresent = classPresent("forge.ai.PlayerControllerAi");
        boolean stockRemoteGuiPresent = classPresent("forge.gamemodes.net.server.RemoteClientGuiGame");
        return "{{"
            + "\\\"protocol\\\":" + jsonString(PROTOCOL) + ","
            + "\\\"message_type\\\":" + jsonString(messageType) + ","
            + "\\\"request_id\\\":" + jsonString(requestId) + ","
            + "\\\"payload\\\":{{"
            + "\\\"verdict\\\":" + jsonString(verdict) + ","
            + "\\\"evidence_class\\\":\\\"RUNTIME_VERIFIED\\\","
            + "\\\"reason\\\":" + jsonString(reason) + ","
            + "\\\"provider\\\":\\\"forge\\\","
            + "\\\"forge_commit\\\":" + jsonString(FORGE_COMMIT) + ","
            + "\\\"forge_tree\\\":" + jsonString(FORGE_TREE) + ","
            + "\\\"forge_version\\\":" + jsonString(FORGE_VERSION) + ","
            + "\\\"generated_abstract_count\\\":" + GENERATED_ABSTRACT_COUNT + ","
            + "\\\"runtime_abstract_count\\\":" + runtimeAbstractCount + ","
            + "\\\"strict_controller_direct_superclass\\\":" + strictDirect + ","
            + "\\\"ai_module_present\\\":" + aiPresent + ","
            + "\\\"stock_remote_gui_present\\\":" + stockRemoteGuiPresent + ","
            + "\\\"rules_core_fixture_execution\\\":\\\"UNSUPPORTED\\\""
            + "}}}}";
    }}

    public static void main(String[] args) throws Exception {{
        String body;
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in))) {{
            body = reader.lines().collect(Collectors.joining("\\n"));
        }}
        String protocol = extract(body, "protocol");
        String requestId = extract(body, "request_id");
        String type = extract(body, "message_type");
        if (!PROTOCOL.equals(protocol) || requestId == null || type == null) {{
            System.out.println(response(requestId, "ERROR", "FAIL", "WS19_PROTOCOL_INPUT_INVALID"));
            System.exit(2);
        }}
        int runtimeAbstractCount = abstractPlayerControllerCount();
        if (runtimeAbstractCount != GENERATED_ABSTRACT_COUNT) {{
            System.out.println(response(requestId, "ERROR", "FAIL", "WS19_CALLBACK_SURFACE_DRIFT"));
            System.exit(3);
        }}
        if (classPresent("forge.ai.PlayerControllerAi") || classPresent("forge.gamemodes.net.server.RemoteClientGuiGame")) {{
            System.out.println(response(requestId, "ERROR", "FAIL", "WS19_PROHIBITED_MODULE_ON_PROVIDER_CLASSPATH"));
            System.exit(4);
        }}
        if ("HANDSHAKE".equals(type)) {{
            System.out.println(response(requestId, "HANDSHAKE_RESULT", "PASS", "WS19_STRICT_ISOLATED_PROBE_READY; rules fixture execution remains unsupported"));
            return;
        }}
        if ("RUN_FIXTURE".equals(type)) {{
            System.out.println(response(requestId, "RUN_FIXTURE_RESULT", "UNSUPPORTED", "WS19_FAIL_CLOSED: Forge rules/DecisionFrame fixture route is not implemented; no AI/default/GUI fallback used"));
            return;
        }}
        System.out.println(response(requestId, "ERROR", "UNSUPPORTED", "WS19_MESSAGE_TYPE_UNSUPPORTED"));
    }}
}}
'''


def remote_defaults(source: str) -> list[dict[str, object]]:
    findings: list[dict[str, object]] = []
    for lineno, line in enumerate(source.splitlines(), start=1):
        for match in REMOTE_DEFAULT_RE.finditer(line):
            findings.append({"line": lineno, "fallback": match.group(1), "text": line.strip()})
    return findings


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--player-controller", type=Path, required=True)
    ap.add_argument("--remote-client-gui", type=Path, required=True)
    ap.add_argument("--output-dir", type=Path, required=True)
    ap.add_argument("--forge-commit", required=True)
    ap.add_argument("--forge-tree", required=True)
    ap.add_argument("--forge-version", required=True)
    args = ap.parse_args()

    pc = args.player_controller.read_text(encoding="utf-8")
    remote = args.remote_client_gui.read_text(encoding="utf-8")
    methods = abstract_methods(pc)
    concrete = concrete_methods(pc)
    defaults = remote_defaults(remote)

    out = args.output_dir
    java_dir = out / "java" / "forge" / "game" / "player"
    java_dir.mkdir(parents=True, exist_ok=True)
    strict_path = java_dir / "StrictExternalPlayerControllerGenerated.java"
    provider_path = java_dir / "Ws19ForgeProbeProvider.java"
    strict_path.write_text(render_strict_controller(pc, methods), encoding="utf-8")
    provider_path.write_text(
        render_probe_provider(
            forge_commit=args.forge_commit,
            forge_tree=args.forge_tree,
            forge_version=args.forge_version,
            abstract_count=len(methods),
        ),
        encoding="utf-8",
    )

    inventory = {
        "schema_version": "ws19-forge-callback-inventory/1.0.0",
        "forge_commit": args.forge_commit,
        "forge_tree": args.forge_tree,
        "forge_version": args.forge_version,
        "player_controller_sha256": sha256_file(args.player_controller),
        "remote_client_gui_sha256": sha256_file(args.remote_client_gui),
        "abstract_method_count": len(methods),
        "abstract_methods": methods,
        "concrete_method_names": concrete,
        "stock_remote_default_findings": defaults,
        "stock_remote_path_qualified": False,
        "strict_generated_controller_policy": "EVERY_ABSTRACT_METHOD_THROWS_WS19_UNROUTED_DECISION_UNLESS_FUTURE_ROUTED",
    }
    inventory_path = out / "callback_inventory.json"
    inventory_path.write_text(
        json.dumps(inventory, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    manifest = {
        "schema_version": "ws19-forge-generated-gpl-artifacts/1.0.0",
        "generated_from": {
            "player_controller": str(args.player_controller),
            "remote_client_gui": str(args.remote_client_gui),
        },
        "artifacts": {
            str(strict_path.relative_to(out)): sha256_file(strict_path),
            str(provider_path.relative_to(out)): sha256_file(provider_path),
            "callback_inventory.json": sha256_file(inventory_path),
        },
        "license_boundary": "Generated Java artifacts are GPL-side qualification artifacts and must not be imported into the proprietary Commander Lab package.",
    }
    (out / "generated_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    print(
        json.dumps(
            {"abstract_method_count": len(methods), "stock_remote_defaults": len(defaults)},
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
